apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9898
#     - port: 9999
#       targetPort: grpc
#       protocol: TCP
#       name: grpc
